services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: branch_task_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: "host=db user=postgres password=password dbname=branch_task_db sslmode=disable"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend